from typing import Any

from pydantic import BaseModel


class ChatResponse(BaseModel):
    """Represents a response generated by the chat model.

    Attributes:
        content (str): The textual content of the response message.
        metadata (dict[str, Any] | None): Optional key-value pairs containing
            additional execution details, metrics, or metadata. Defaults to None.
    """

    content: str
    metadata: dict[str, Any] | None = None
