from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class MessageSchema(BaseModel):
    """Represents an individual message within a conversation.

    Attributes:
        role (str): The role of the message sender (e.g., 'user', 'assistant', 'system').
        content (str): The textual body of the message.
        metadata (Optional[Dict[str, Any]]): Additional contextual key-value metadata
            associated with the message. Defaults to an empty dictionary.
    """

    role: str
    content: str
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict)


class ChatRequestSchema(BaseModel):
    """Represents the request payload for chat interactions.

    Attributes:
        history (List[MessageSchema]): The sequence of messages representing the conversation history.
    """

    history: List[MessageSchema]


class ChatResponseSchema(BaseModel):
    """Represents the response payload returned by the chat API.

    Attributes:
        content (str): The primary output content generated by the assistant.
        metadata (Optional[Dict[str, Any]]): Additional metadata related to the response processing,
            such as token usage or execution statistics. Defaults to an empty dictionary.
    """

    content: str
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict)
