from typing import Any, Dict, Optional
from pydantic import BaseModel, Field


class ChatResponseSchema(BaseModel):
    """Represents the response payload returned by the chat API.

    Attributes:
        content (str): The primary output content generated by the assistant.
        metadata (Optional[Dict[str, Any]]): Additional metadata related to the response 
            processing, such as token usage or execution statistics. Defaults to an 
            empty dictionary.
    """

    content: str
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict)