from ai_assistant_platform.config.logging_config import (
    get_logger,
)
from ai_assistant_platform.llm.llm_service import (
    LLMService,
)
from ai_assistant_platform.prompts.writer_prompt import (
    build_writer_prompt,
)

logger = get_logger(__name__)


class WriterAgent:
    """Generates the final localized response presented to the user.

    Attributes:
        _llm_service (LLMService): Service instance used for generating language model outputs.
    """

    def __init__(
        self,
        llm_service: LLMService,
    ) -> None:
        """Initializes the WriterAgent with an LLM service.

        Args:
            llm_service (LLMService): Service handling interaction with language models.
        """
        self._llm_service = llm_service
        logger.info("WriterAgent initialized")

    def generate_response(
        self,
        result: float,
        language: str,
    ) -> dict:
        """Generates a localized natural language response for a mathematical result.

        Args:
            result (float): The numerical output of the mathematical evaluation.
            language (str): Target language code for the response output.

        Returns:
            dict: A payload containing the generated response content string and token usage metadata.
        """

        formatted_result = self._format_result(
            result,
        )

        logger.debug(
            "Generating user response result=%s language=%s",
            formatted_result,
            language,
        )

        prompt = build_writer_prompt(
            result=formatted_result,
            language=language,
        )

        response = self._llm_service.generate_response(
            messages=[
                {
                    "role": "system",
                    "content": "You are a multilingual mathematical assistant.",
                },
                {
                    "role": "user",
                    "content": prompt,
                },
            ],
        )

        logger.info(
            "User response generated language=%s",
            language,
        )

        return {
            "content": response.get("content", ""),
            "usage": response.get("usage", {}),
        }

    def generate_error_response(
        self,
        user_message: str,
        error: str,
    ) -> dict:
        """Generates a user-facing localized error message based on an internal failure.

        Args:
            user_message (str): The raw input message from the user used to infer target language.
            error (str): Description or message detailing the internal error encountered.

        Returns:
            dict: Response dictionary generated by the LLM containing the user-facing error message.
        """

        logger.warning(
            "Generating localized error response error=%s",
            error,
        )

        prompt = f"""
User message:
{user_message}

Internal error:
{error}

Rules:
- Detect the user's language.
- Reply in the same language.
- Be concise.
- Never expose implementation details.
- Return only the final answer.
"""

        response = self._llm_service.generate_response(
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You generate multilingual mathematical error messages."
                    ),
                },
                {
                    "role": "user",
                    "content": prompt,
                },
            ],
        )

        logger.info("Localized error response generated")

        return response

    def _format_result(
        self,
        value: float,
    ) -> str:
        """Formats a numerical result as an integer string if whole, or float string otherwise.

        Args:
            value (float): The numerical value to format.

        Returns:
            str: String representation of the formatted number.
        """

        if float(value).is_integer():
            return str(
                int(value),
            )

        return str(value)
