from ai_assistant_platform.config.settings import (
    LLM_PROVIDER,
)

from ai_assistant_platform.llm.provider_factory import (
    ProviderFactory,
)


class LLMService:
    """
    Service responsible for interacting with the configured language model
    provider.

    This class provides a stable interface for the rest of the application,
    abstracting provider selection and delegating requests to the configured
    LLM implementation.

    Attributes:
        provider:
            Instance of the configured language model provider created by
            the provider factory.
    """

    def __init__(self) -> None:
        """
        Initialize the service with the configured LLM provider.
        """

        self.provider = ProviderFactory.create(LLM_PROVIDER)

    def generate_response(
        self,
        messages: list[dict[str, str]],
    ) -> str:
        """
        Generate a response from the configured language model provider.

        Args:
            messages:
                A sequence of chat messages formatted according to the
                provider's expected interface.

        Returns:
            The text response generated by the configured language model.
        """

        return self.provider.generate_response(messages)
