from ai_assistant_platform.api.exceptions import EmptyConversationError
from ai_assistant_platform.api.schemas import ChatRequest
from ai_assistant_platform.api.schemas import ChatResponse
from ai_assistant_platform.orchestrators.chatbot_orchestrator import (
    ChatbotOrchestrator,
)


class ChatService:
    """Provides business logic services for chat interactions.

    Attributes:
        _orchestrator (ChatbotOrchestrator): The orchestrator instance used to process
            and coordinate chat operations.
    """

    def __init__(
        self,
        orchestrator: ChatbotOrchestrator,
    ) -> None:
        """Initializes the ChatService with a chatbot orchestrator.

        Args:
            orchestrator (ChatbotOrchestrator): The orchestrator instance responsible
                for coordinating chatbot execution.
        """
        self._orchestrator = orchestrator

    async def send(
        self,
        request: ChatRequest,
    ) -> ChatResponse:
        """Processes an incoming chat request, extracts message context, and delegates
        execution to the chatbot orchestrator.

        Args:
            request (ChatRequest): The incoming request payload containing the conversation history.

        Returns:
            ChatResponse: The response generated by the orchestrator containing message content
                and metadata.

        Raises:
            EmptyConversationError: If the provided conversation history is empty.
        """
        if not request.history:
            raise EmptyConversationError()

        history = [
            {
                "role": message.role,
                "content": message.content,
                "metadata": message.metadata or {},
            }
            for message in request.history
        ]

        user_message = history[-1]["content"]

        response = self._orchestrator.process_message(
            user_message=user_message,
            conversation_history=history,
        )

        return ChatResponse(
            content=response["response"],
            metadata=response["metadata"],
        )
