from abc import ABC, abstractmethod


class BaseLLMProvider(ABC):
    """
    Abstract base class for language model providers.

    All provider implementations must inherit from this class and
    implement the response generation interface. This abstraction
    ensures a consistent API across different language model providers,
    allowing them to be used interchangeably throughout the application.
    """

    @abstractmethod
    def generate_response(
        self,
        messages: list[dict[str, str]],
    ) -> str:
        """
        Generate a response from the language model.

        Args:
            messages:
                A sequence of chat messages formatted according to the
                provider's expected interface.

        Returns:
            The text response generated by the language model.

        Raises:
            NotImplementedError:
                Raised if a subclass does not implement this method.
        """

        raise NotImplementedError
