from ai_assistant_platform.llm.providers.base_provider import (
    BaseLLMProvider,
)


class GeminiProvider(BaseLLMProvider):
    """
    Language model provider for the Gemini API.

    This class implements the provider interface for interacting with
    Gemini models. The implementation is currently a placeholder and
    must be completed before it can be used.
    """

    def generate_response(
        self,
        messages: list[dict[str, str]],
    ) -> str:
        """
        Generate a response using the Gemini language model.

        Args:
            messages:
                A sequence of chat messages formatted according to the
                Gemini provider interface.

        Returns:
            The text response generated by the Gemini model.

        Raises:
            NotImplementedError:
                Raised because the provider has not been implemented yet.
        """

        raise NotImplementedError("Gemini provider not implemented yet.")
