from ai_assistant_platform.llm.providers.base_provider import (
    BaseLLMProvider,
)


class OllamaProvider(BaseLLMProvider):
    """
    Language model provider for the Ollama local inference API.

    This class implements the provider interface for interacting with
    locally hosted models via Ollama. The current implementation is a
    placeholder and must be completed before production use.
    """

    def generate_response(
        self,
        messages: list[dict[str, str]],
    ) -> str:
        """
        Generate a response using a locally hosted Ollama model.

        Args:
            messages:
                A sequence of chat messages formatted according to the
                Ollama provider interface.

        Returns:
            The text response generated by the Ollama model.

        Raises:
            NotImplementedError:
                Raised because the provider has not been implemented yet.
        """

        raise NotImplementedError("Ollama provider not implemented yet.")
