from typing import Annotated

from fastapi import APIRouter
from fastapi import Depends

from ai_assistant_platform.api.dependencies import (
    get_chat_service,
)
from ai_assistant_platform.api.schemas import ChatRequest
from ai_assistant_platform.api.schemas import ChatResponse
from ai_assistant_platform.services import ChatService

router = APIRouter(
    prefix="/chat",
    tags=["Chat"],
)


@router.post(
    "",
    response_model=ChatResponse,
)
async def send_message(
    request: ChatRequest,
    service: Annotated[
        ChatService,
        Depends(get_chat_service),
    ],
) -> ChatResponse:
    """Handles incoming chat HTTP requests and delegates processing to the chat service.

    Args:
        request (ChatRequest): The payload containing conversation history and message context.
        service (ChatService): The injected service instance responsible for executing
            the chat logic.

    Returns:
        ChatResponse: The response payload containing content and metadata generated by
            the assistant.

    Raises:
        EmptyConversationError: Raised indirectly via the service layer if the conversation
            history is empty.
    """
    return await service.send(
        request=request,
    )
